name: Flutter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable web configuration
        run: flutter config --enable-web
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting issues
        run: flutter format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze .
      - name: Build
        run: flutter build web --release
