name: Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: 'parallax-discord'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          procfile: 'web: node ./dist/main.js'
          buildpack: 'https://github.com/heroku/heroku-buildpack-nodejs.git'
          healthcheck: 'https://parallax-discord.herokuapp.com/status'
          checkstring: 'online'
          rollbackonhealthcheckfailed: true
          delay: 30
        env:
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_DB_URI: ${{secrets.DB_URI}}
          HD_GOOGLE_KEY: ${{secrets.GOOGLE_KEY}}
          HD_NEW_RELIC_APP_NAME: 'parallax-discord'
          HD_NEW_RELIC_LICENSE_KEY: ${{secrets.NEW_RELIC_LICENSE_KEY}}
          HD_NEW_RELIC_NO_CONFIG_FILE: 'true'
          HD_SPOTIFY_ID: ${{secrets.SPOTIFY_ID}}
          HD_SPOTIFY_SECRET: ${{secrets.SPOTIFY_SECRET}}
