name: TSCompiler

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tscompiler:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --omit=dev
      - name: Run compiler
        run: npm run build
